server:
  shutdown: graceful
  port: 8080
  tomcat:
    connection-timeout: 5m
logging:
  config: classpath:log/logback-spring-${SYSTEM_ENV}.xml
spring:
  application.name: aifoundry
  profiles:
    group:
      default:
      test:
      prod:
management:
  endpoints:
    access:
      default: none
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        step: 2m
  info:
    java:
      enabled: true